name: Blob storage website CI

on:
  push:
    branches:
      - release  # Desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.4

      - name: Install dependencies & build React app
        run: npm install && npm run build

      - name: Log in with Azure
        uses: Azure/login@v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob Storage
        uses: Azure/cli@v2.1.0
        with:
          azcliversion: latest
          inlineScript: az storage blob upload-batch -s "dist" -d '$web' --account-name store0r --overwrite true --auth-mode login

      - name: Logout of Azure
        run: az logout
        if: always()
