name: Blob storage website CI

on:
  push:
    branches:
      - release  # Desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch -s /dist -d '$web' --account-name store0r --overwrite

      - name: Logout of Azure
        run: |
          az logout
